SETTINGS_DOCTYPE_NAME = "ZRA SIS Settings"  # Holds credentials, URLs, tokens
ROUTES_TABLE_CHILD_DOCTYPE_NAME ="ZRA SIS Route Item"
ROUTES_TABLE_DOCTYPE_NAME ="ZRA SIS Routes"


TAXATION_TYPE_DOCTYPE_NAME = "ZRA SIS Taxation Type Codes"
ITEM_CLASSIFICATIONS_DOCTYPE_NAME = "ZRA SIS Item Classification Codes"
ITEM_TYPE_DOCTYPE_NAME = "ZRA SIS Item Type Codes"
COUNTRY_DOCTYPE_NAME = "ZRA SIS Country Codes"
PACKAGING_UNIT_DOCTYPE_NAME = "ZRA SIS Packaging Unit Codes"
UNIT_OF_QUANTITY_DOCTYPE_NAME = "ZRA SIS Quantity Unit Codes"